### ISSUE TITLE
Questions: Should all of the wiki be ported to void-docs?

### ISSUE THREAD

**Issue by Frick-David** [void-linux/void-docs#161]
I am trying to port everything needed from the wiki to the docs over time. Can I get some input on what should be ported first? I am trying to finish up steam, and docker, then will be moving on to whatever else is deemed most important. Is there anything not to port from the wiki?

**Comment by flexibeast** [comment]
i'd also be interested in knowing this. i've just started working on porting and updating some of the musl stuff (#130), but it would be good to know if there are other particular wiki pages that should be prioritised, or whether wiki porting is actually less important than addressing other [void-docs issues](https://github.com/void-linux/void-docs/issues).

**Comment by anaggh** [comment]
I feel wiki.voidlinux.org should be shutdown. Irritating to search docs+wiki separately.

From what I can see here https://wiki.voidlinux.org/Special:AllPages there are about 244 pages.

Steps we could follow:
* Make wiki readonly
* Backup the entire wiki (sql+webdir) and archive it.
* Export all the wiki pages to markdown format and move everything to docs.voidlinux.org under `archived`
* Delete pages that were already migrated.
* Delete old obsolete pages that no longer work.
* Update and move pages to the correct sections.
* Shutdown wiki.voidlinux.org instance and add a redirect to docs.voidlinux.org

**Comment by flexibeast** [comment]
@anaggh: Yes, the plan is indeed to shut down the wiki: see #104, which also includes discussion of some of the things you've mentioned. Also, check [the issues section of this repo](https://github.com/void-linux/void-docs/issues/) for both open and closed issues regarding moving wiki content to the Handbook. Finally, in November last year i [submitted a PR for a deprecation notice to be added to the wiki](https://github.com/void-linux/void-wiki/pull/1), since the wiki is appearing above the Handbook in search results.

**Comment by Vaelatern** [comment]
Freezing the wiki would be good, but not all wiki content is worth moving over. Any wiki content that is void-specific should definitely be available on docs.

**Comment by Frick-David** [comment]
Okay, thanks!

**Comment by bobertlo** [comment]
Yes, I think the wiki should be shut down, or at least have a banner on the top telling people it is deprecated. We don't have a dump of it that we can redistribute but the content is all covered on archive.org. If there was a sitemap we could crawl it and make sure, but when I checked months ago everything was covered (in a very anecdotal sense of the word everything)

We are still trying to limit the scope of the handbook, so a lot of the content from the wiki is not going to make the cut. I am still wondering if we should have a second collection of "community" guides, as has been discussed elsewhere in different forms, since there is useful information that does not make the cut.

For now the docs are definitely not *complete*, but we are also not trying to just stick every piece of writing from the wiki in there either.

I have recently self isolated and will try to work through the backlog of PRs as quickly as I can. I need to set up WFH and I am sick though so it's not a ton of time, just a lot more than before.

Thank you all for all the recent contributions.

**Comment by bobertlo** [comment]
https://docs.voidlinux.org/howtoread/index.html

This page has a useful description of the attitude for what we are trying to inlude in the docs. It was more or less agreed to at the time by the people active on the docs.

I also want to mention that it's great to get all the info from the wiki onto PRs for the docs, but there will be an editing process because it looks like a lot of this is coming more or less copy/pasted and the point of this project is to raise the bar. I am NOT criticising the contributions! I just want to say that we try to edit before things are merged.

**Comment by flexibeast** [comment]
@bobertlo: Further to what you wrote in [this comment above](https://github.com/void-linux/void-docs/issues/161#issuecomment-600620225), are you in a position to be able to merge https://github.com/void-linux/void-wiki/pull/1? At any rate, do you know of any blockers to doing so? i'm happy to try to address any potential blockers ....

**Comment by bobertlo** [comment]
@flexibeast I am not, but I pinged people who are

**Comment by anaggh** [comment]
There are 204 pages instead of 244 (Others were redirects). I wrote a migration script from html > markdown.

Attached is the markdown output
[wiki-md.zip](https://github.com/void-linux/void-docs/files/4411198/wiki-md.zip)

Source to convert if needed: https://github.com/anaggh/void-wiki-export

**Comment by bobertlo** [comment]
Okay, I think this issue has been resolved. Thanks @anaggh
