### ISSUE TITLE
Missing AMD graphics section

### ISSUE THREAD

**Issue by st3r4g** [void-linux/void-docs#310]
- explain `xf86-video-ati` vs `xf86-video-amdgpu`

**Comment by ericonr** [comment]
Do you think this could fit under Xorg? Don't want to add another page.

**Comment by st3r4g** [comment]
My idea for the graphics docs (when I added the sections for Intel and NVIDIA Optimus) was to organize things by hardware configuration rather than topic. So it makes sense to me to have sections for all 3 big vendors (AMD currently missing). I believe there are other things worth mentioning, from video acceleration to openCL drivers.
If you think it's too obvious stuff or it should be organized in a different way we can discuss it

**Comment by ericonr** [comment]
Hmm documenting the opencl stuff could be interesting. For intel and nvidia as well (I can do those, I think).

Do we have all the AMD vulkan drivers? Could be interesting to mention them as well.

Regarding splitting into several pages, the thing is that usually the content is small and having to navigate several pages to access all of it can get tiring quick. However, since for graphics a person will usually have only one of them, I think it might be fine.

**Comment by flexibeast** [comment]
Fwiw, i tend to agree with @st3r4g here: individual pages for the "big three" makes sense to me, particularly if there's information that's not Xorg specific, but could apply to e.g. Wayland compositors as well (is there?). We certainly want to avoid tiny pages as much as we can (there are already a number that could perhaps be consolidated into larger pages), but i think we should also try to avoid overly-large pages where possible.
