### ISSUE TITLE
Add runit-void specific ZFS requirement

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-docs#397]
The current runit core service for mounting filesystems only tries to mount ZFS filesystems during boot if `/etc/zfs/zpool.cache` exists. This behavior should be documented in the docs. Should this also be solved in packaging, by providing a script to generate the cache? Or should the documentation include the complete command as well?

pinging @ahesford and @zdykstra 

I'm not super keen on the idea of having a script, but wanted to mention it.

Relevant for #206 , at least.

**Comment by ahesford** [comment]
Two things:

1. I don't think `core-services/03-filesystems.sh` does the right thing with respect to ZFS mounts by demanding `/etc/zfs/zpool.cache` exist, but I don't quite know what the right course would be.

2. Given that `/etc/zfs/zpool.cache` is required for now, it definitely should be mentioned in the ZFS docs like #206. Normally, ZFS will update the cache every time a pool is imported. This doesn't apply to the root because it is imported before the root is available.

I don't think a script should be provided, because all that is required is a single line:
```
zpool set cachefile=/etc/zfs/zpool.cache <pool>
```
If the root dataset is mounted somewhere other than `/`, the dirname can be updated to include the mountpoint as appropriate.

**Comment by ericonr** [comment]
> I don't think core-services/03-filesystems.sh does the right thing with respect to ZFS mounts by demanding /etc/zfs/zpool.cache exist, but I don't quite know what the right course would be.

Indeed! That check has been there since ZFS was added to `03-filesystems.sh`, and doesn't seem to include any explanations as to why. I can open an issue in the repo to discuss it.

**Comment by ahesford** [comment]
Please do. Tag zdykstra and me, maybe Vaelatern and others you know have an interest in ZFS. It would be nice to hash out the "right" way to import and mount when `zpool.cache` does not exist.

**Comment by ericonr** [comment]
Closing when void-runit gets a new release. Thanks @ahesford and @zdykstra!
